### PR TITLE
add functionality Emoji Icons in Chatbot Messages

### PR DESCRIPTION
**Pull request by YassineAzedine**

### CODE REVIEW

**Comment by YassineAzedine** [comment]
[add functionality Emoji Icons in Chatbot Messages](https://github.com/Abdullah-moiz/mern-chat-app/pull/3/commits/419f2e793fe3f927bf2b08f01ea6abf6f45f264b)

**Comment by Abdullah-moiz** [comment]
Hey @YassineAzedine  Thanks for adding this , can you please provide me a screenshot , or you can directly update the readme file as well like i did

**Comment by YassineAzedine** [comment]
Hey @Abdullah-moiz Here are the screenshots for this functionality. 
Capture d’écran (10)
Capture d’écran (11)
Capture d’écran (12)

**Comment by Abdullah-moiz** [comment]
Thanks for the contribution I merged your PR

**Comment by Abdullah-moiz** [comment]
image

**Pull request merged**
